#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true

# Force the application to prefer IPv4 addresses
java.net.preferIPv4Stack=true
java.net.preferIPv6Addresses=false


logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG


spring.application.name=eureka-server
server.port=8761
#eureka.server.enableSelfPreservation=false

# Interval to fetch registry data from Eureka server
eureka.client.registryFetchIntervalSeconds=30

# Interval to send heartbeat to Eureka server
eureka.instance.leaseRenewalIntervalInSeconds=120
eureka.instance.leaseExpirationDurationInSeconds=120


